// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7UntaF88bVzjbCHAnJgNWwijZfnqbSSo',
    appId: '1:852414368115:web:a43782dbf7006711bb5d06',
    messagingSenderId: '852414368115',
    projectId: 'loginflutter-adbde',
    authDomain: 'loginflutter-adbde.firebaseapp.com',
    storageBucket: 'loginflutter-adbde.appspot.com',
    measurementId: 'G-52JQHCXPSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8AMgPBj-2hkkI2rn82euJ4ryxPMoPxg',
    appId: '1:852414368115:android:43b83cf70a6d789cbb5d06',
    messagingSenderId: '852414368115',
    projectId: 'loginflutter-adbde',
    storageBucket: 'loginflutter-adbde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAP9JrFEsPjz-QgnfjabGMEvnvfoVyMi4',
    appId: '1:852414368115:ios:fad043c720571bc2bb5d06',
    messagingSenderId: '852414368115',
    projectId: 'loginflutter-adbde',
    storageBucket: 'loginflutter-adbde.appspot.com',
    iosClientId: '852414368115-ut94vvm5mstmhvk1ivjq6r3upsjpbkja.apps.googleusercontent.com',
    iosBundleId: 'com.example.layout1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAP9JrFEsPjz-QgnfjabGMEvnvfoVyMi4',
    appId: '1:852414368115:ios:fad043c720571bc2bb5d06',
    messagingSenderId: '852414368115',
    projectId: 'loginflutter-adbde',
    storageBucket: 'loginflutter-adbde.appspot.com',
    iosClientId: '852414368115-ut94vvm5mstmhvk1ivjq6r3upsjpbkja.apps.googleusercontent.com',
    iosBundleId: 'com.example.layout1',
  );
}
